name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
        
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
